apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume1
  labels:
    failure-domain.beta.kubernetes.io/zone: us-west-2a
spec:
  flexVolume:
    driver: flexvolume/ebs
    fsType: xfs
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ebs
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 50Gi
