apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-httpbin-0
spec:
  volumeName: volume1
  storageClassName: ebs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
