#!/bin/bash

# Notes:
# Requires: aws cli, jq
# $REGION must be set

NVME_DEVICES=(/dev/nvme1n1 /dev/nvme2n1)

usage() {
  err "Invalid usage. Usage: "
  err "\t$0 init"
  err "\t$0 attach <json params> <nodename>"
  err "\t$0 detach <mount device> <nodename>"
  err "\t$0 waitforattach <mount device> <json params>"
  err "\t$0 mountdevice <mount dir> <mount device> <json params>"
  err "\t$0 unmountdevice <mount dir>"
  err "\t$0 isattached <json params> <nodename>"
  exit 1
}

err() {
  debug "ERROR $*"
  echo -ne $* 1>&2
}

log() {
  debug "$*"
  echo -ne $* >&1
}

# log file
debug() {
  echo "$(date) $*" >> /var/log/flex-ebs.log
}

# called on master
attach() {
  debug "attach $@"
  JSON_PARAMS=$1
  NODE_NAME=$2
  VOLUME_NAME=$(echo ${JSON_PARAMS} | jq -r '.["kubernetes.io/pvOrVolumeName"]')

  # find volume by Name tag
  VOLUMEID=$(aws ec2 describe-volumes --region $REGION --filters "Name=tag-key,Values=Name,Name=tag-value,Values=$VOLUME_NAME" --query "Volumes[].VolumeId" --output text)
  # find instance by local dns
  INSTANCE_JSON=$(aws ec2 describe-instances --region $REGION --filters "Name=private-dns-name,Values=${NODE_NAME}.*")

  # compute next attach device
  ALL_DEVICES=$(printf "%s\n" {/dev/sdf,/dev/sdg,/dev/sdh,/dev/sdi,/dev/sdj,/dev/sdk,/dev/sdl} | sort)
  EXISTING_DEVICES=$(echo $INSTANCE_JSON | jq -r .Reservations[].Instances[].BlockDeviceMappings[].DeviceName | sort)
  ATTACH_DEVICE=$(comm -23 <(echo -e "$ALL_DEVICES") <(echo -e "$EXISTING_DEVICES") | head -1)

  # do attach
  INSTANCE_ID=$(echo $INSTANCE_JSON |jq -r .Reservations[].Instances[].InstanceId)
  OUTPUT=$(aws ec2 attach-volume --region $REGION --volume-id "$VOLUMEID" --instance-id "$INSTANCE_ID" --device "$ATTACH_DEVICE")

  if [ $? -ne 0 ]; then
    debug "attach $OUTPUT"
    err "{ \"status\": \"Failure\", \"message\": \"Error Attaching $VOLUME_NAME($VOLUMEID) As $ATTACH_DEVICE To ${NODE_NAME}/${INSTANCE_ID}\"}"
    exit 1
  else
    log "{\"status\": \"Success\", \"device\":\"${VOLUMEID}\", \"message\": \"Attached $VOLUME_NAME($VOLUMEID) As $ATTACH_DEVICE To ${NODE_NAME}/${INSTANCE_ID}\"}"
    exit 0
  fi
}

#called on master periodically after calling attach()
isattached() {
  debug "isattached $@"
  JSON_PARAMS=$1
  NODE_NAME=$2
  VOLUME_NAME=$(echo ${JSON_PARAMS} | jq -r '.["kubernetes.io/pvOrVolumeName"]')

  VOLUME_JSON=$(aws ec2 describe-volumes --region $REGION --filters "Name=tag-key,Values=Name,Name=tag-value,Values=$VOLUME_NAME")
  VOLUMEID=$(echo $VOLUME_JSON | jq -r .Volumes[].VolumeId)
  ATTACHED_INSTANCE_ID=$(echo $VOLUME_JSON | jq -r .Volumes[].Attachments[].InstanceId)
  ATTACHED_DEVICE=$(echo $VOLUME_JSON | jq -r .Volumes[].Attachments[].Device)
  INSTANCE_ID=$(aws ec2 describe-instances --region $REGION --filters "Name=private-dns-name,Values=${NODE_NAME}.*" --query 'Reservations[*].Instances[*].InstanceId'|jq -r .[0][0])

  if [ "$ATTACHED_INSTANCE_ID" == "$INSTANCE_ID" ]; then
    log "{\"status\": \"Success\", \"attached\":true, \"message\": \"Volume $VOLUME_NAME($VOLUMEID) Attached As $ATTACHED_DEVICE To $NODE_NAME($INSTANCE_ID)\"}"
    exit 0
  else
    err "{\"status\": \"Failure\", \"attached\":false, \"message\": \"Volume $VOLUME_NAME($VOLUMEID) Not Attached To $NODE_NAME($INSTANCE_ID)\"}"
    exit 1
  fi
}

#called on node, VOLUMEID comes from attach() DEVICE field
waitforattach() {
  debug "waitforattach $@"
  VOLUMEID=$1
  JSON_PARAMS=$2
  VOLUME_NAME=$(echo ${JSON_PARAMS} | jq -r '.["kubernetes.io/pvOrVolumeName"]')

  # find DEVICE by reading the /dev/disk/by-id/*$VOLUMEID symlink
  DEVICE=$(readlink -f $(ls /dev/disk/by-id/*${VOLUMEID/-/}))

  end=$((SECONDS+120))
  while [ $SECONDS -lt $end ]; do
    if [ -b "$DEVICE" ] ; then
      log "{\"status\": \"Success\", \"device\":\"${DEVICE}\"}"
      exit 0
    fi
  done

  err "{ \"status\": \"Failure\", \"message\": \"Volume ${VOLUME_NAME} not attached to device ${DEVICE}\" \"}"
  exit 1
}

#called on node, DEVICE comes from waitforattach()
mountdevice() {
  debug "mountdevice $@"
  MNTPATH=$1
  DEVICE=$2
  JSON_PARAMS=$3
  VOLUME_NAME=$(echo ${JSON_PARAMS} | jq -r '.["kubernetes.io/pvOrVolumeName"]')
  FSTYPE=$(echo ${JSON_PARAMS} | jq -r '.["kubernetes.io/fsType"]')

  if [ ! -b "${DEVICE}" ]; then
    err "{\"status\": \"Failure\", \"message\": \"Device ${DEVICE} Not Found\"}"
    exit 1
  fi

  if [ $(ismounted) -eq 1 ] ; then
    log "{\"status\": \"Success\"}"
    exit 0
  fi

  VOLFSTYPE=`blkid -o udev ${DEVICE} 2>/dev/null`
  if [ "${VOLFSTYPE}" == "" ]; then
    mkfs.${FSTYPE} -f ${DEVICE} >/dev/null 2>&1
    if [ $? -ne 0 ]; then
      err "{ \"status\": \"Failure\", \"message\": \"Error Calling mkfs.${FSTYPE} -f ${DEVICE}\"}"
      exit 1
    fi
  fi

  mkdir -p ${MNTPATH} &> /dev/null
  mount -t ${FSTYPE} ${DEVICE} ${MNTPATH} &> /dev/null
  if [ "${FSTYPE}" == "xfs" ]; then
    xfs_growfs ${MNTPATH} &> /dev/null
  fi

  if [ $? -ne 0 ]; then
    err "{ \"status\": \"Failure\", \"message\": \"Error Calling mount -t ${FSTYPE} ${DEVICE} ${MNTPATH}\"}"
    exit 1
  else
    log "{\"status\": \"Success\", \"message\": \"Successfully Called mount -t ${FSTYPE} ${DEVICE} ${MNTPATH}\"}"
    exit 0
  fi
}

#called on node
unmountdevice() {
  debug "unmountdevice $@"
  MNTPATH=$1

  if [ ! -d ${MNTPATH} ]; then
    log "{\"status\": \"Success\", \"message\": \"Mount ${MNTPATH} Not Found\"}"
    exit 0
  fi

  umount ${MNTPATH} &> /dev/null

  if [ $? -ne 0 ]; then
    err "{ \"status\": \"Failed\", \"message\": \"Error Calling umount ${MNTPATH}\"}"
    exit 1
  else
    log "{\"status\": \"Success\", \"message\": \"Successfully Called umount ${MNTPATH}\"}"
    exit 0
  fi
}

#called on master
detach() {
  debug "detach $@"
  #JSON_PARAMS=$1, should really be same as attach
  PV_NAME=$1
  NODE_NAME=$2
  #hack - make sure PV_NAME is also the VOLUME_NAME
  VOLUME_NAME=$PV_NAME

  #find volume by Name tag
  VOLUMEID=$(aws ec2 describe-volumes --region $REGION --filters "Name=tag-key,Values=Name,Name=tag-value,Values=$VOLUME_NAME" --query 'Volumes[*].VolumeId' --output text)

  #don't detach if state is available
  STATE=$(aws ec2 describe-volumes --region $REGION --volume-ids "$VOLUMEID" | jq -r '.Volumes[].State')
  if [ "$STATE" == "available" ]; then
    log "{\"status\": \"Success\", \"message\": \"Volume $VOLUME_NAME($VOLUMEID) state is $STATE\"}"
    exit 0
  fi

  OUTPUT=$(aws ec2 detach-volume --region $REGION --volume-id "$VOLUMEID")

  if [ $? -ne 0 ]; then
    debug "detach" "$OUTPUT"
    err "{\"status\": \"Failure\", \"message\": \"Error detaching volume $VOLUME_NAME($VOLUMEID) from $NODE_NAME\"}"
    exit 1
  else
    log "{\"status\": \"Success\", \"message\": \"Volume $VOLUME_NAME($VOLUMEID) detached from $NODE_NAME\"}"
    exit 0
  fi

}

getvolumename() {
  debug "getvolumename $@"
  JSON_PARAMS=$1
  VOLUME_NAME=$(echo ${JSON_PARAMS} | jq -r '.["kubernetes.io/pvOrVolumeName"]')

  log "{\"status\": \"Success\", \"volumeName\": \"$VOLUME_NAME\"}"
  exit 0
}

op=$1

if [ "$op" = "init" ]; then
  debug "init"
  log "{\"status\":\"Success\",\"capabilities\":{\"attach\":true}}"
  exit 0
fi

if [ $# -lt 2 ]; then
  usage
fi

shift

case "$op" in
  attach)
    attach $*
    ;;
  detach)
    detach $*
    ;;
  waitforattach)
    waitforattach $*
    ;;
  isattached)
    isattached $*
    ;;
  mountdevice)
    mountdevice $*
    ;;
  unmountdevice)
    unmountdevice $*
    ;;
  # getvolumename)
  #   getvolumename $*
  #   ;;
  *)
    debug "$op"
    log "{ \"status\": \"Not supported\" }"
    exit 0
esac

exit 1